my_reddit/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  root to: 'subs#index'
  resources :subs
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    post :upvote
    post :downvote
  end
  resources :comments, only: [:create, :show, :destroy]

end

my_reddit/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :bigint(8)        not null, primary key
#  content           :string           not null
#  author_id         :integer          not null
#  post_id           :integer          not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  parent_comment_id :integer
#

class Comment < ApplicationRecord

    validates :content, :author_id, :post_id, presence: true
    # validates :parent_comment, :child_comments, optional: true

    belongs_to :author,
    class_name: :User,
    foreign_key: :author_id

    belongs_to :post

    belongs_to(
        :parent_comment,
        foreign_key: :parent_comment_id,
        class_name: 'Comment',
        optional: true
    )

    has_many :child_comments,
    foreign_key: :parent_comment_id,
    class_name: :Comment

    has_many :votes, as: :votable
end

my_reddit/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create

        @comment = Comment.new(comment_params)
        @comment.author_id = current_user.id
        if @comment.save
            redirect_to post_url(@comment.post)
        else
            flash[:errors] = @comment.errors.full_messages
            render :new
        end
    end

    def show
        @comment = Comment.find(params[:id])
    end

    def new
    end

    private
    def comment_params
        params.require(:comment).permit(:content, :post_id, :parent_comment_id)
    end
end

my_reddit/app/helpers/comments_helper.rb
module CommentsHelper
end

my_reddit/app/views/comments/new.html.erb
<h1>New Comment!</h1>

<form action="<%=comments_url%>" method="post">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <label for="content">Content</label>
    <textarea id="content" name="comment[content]"></textarea>
    <input type="hidden" name="comment[post_id]" value="<%=params[:post_id]%>">
    <input type="submit" value="Submit">
</form>

my_reddit/app/views/comments/show.html.erb
<h1>New Reply Comment</h1>

<form action="<%=comments_url%>" method="post">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <label for="content">Content</label>
    <textarea id="content" name="comment[content]"></textarea>
    <input type="hidden" name="comment[post_id]" value="<%=@comment.post_id%>">
    <input type="hidden" name="comment[parent_comment_id]" value="<%= params[:id] %>">
    <input type="submit" value="Submit">
</form>