my_reddit/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  root to: 'subs#index'
  resources :subs
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    post :upvote
    post :downvote
  end
  resources :comments, only: [:create, :show, :destroy]

end

my_reddit/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  url        :string
#  content    :string
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
    validates :title, :author_id, presence: true

    has_many :subtags, dependent: :destroy

    has_many :subs,
    through: :subtags,
    source: :sub

    belongs_to(
        :author,
        class_name: 'User',
        foreign_key: :author_id
    )

    has_many :comments

    has_many :votes, as: :votable

    def top_level_comments
        self.comments.where(parent_comment_id: nil)
    end

    def comments_by_parent_id
        comments = Hash.new { |h,k| h[k] = [] }
        self.comments.each do |comment|
            comments[comment.parent_comment_id] << comment
        end
        comments
    end
end

my_reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @all_comments = @post.comments_by_parent_id
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if current_user.id == @post.author_id && @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy

  end

  def upvote
    @post = Post.find(params[:post_id])
    @all_comments = @post.comments_by_parent_id
    Vote.create(value: 1, votable_type: Post, votable_id: params[:post_id])
    render :show
  end

  def downvote
    @post = Post.find(params[:post_id])
    @all_comments = @post.comments_by_parent_id
    Vote.create(value: -1, votable_type: Post, votable_id: params[:post_id])
    render :show
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

my_reddit/app/helpers/posts_helper.rb
module PostsHelper
end

my_reddit/app/views/posts/_comment_tree.html.erb
<ul>
    <% all_comments[parent_comment.id].each do |child| %>
        <li><a href="<%=comment_url(child)%>"><%= child.content %></a></li>
        <%= render 'comment_tree', parent_comment: child, all_comments: all_comments %>
    <%end%>
</ul>

my_reddit/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<form action="<%=post_url%>" method="post">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <label for="title">Title</label>
    <input type="text" id="title" name="post[title]" value="<%=@post.title%>">
    <br>
    <label for="url">URL</label>
    <input type="text" id="url" name="post[url]" value="<%=@post.url%>">
    <br>
    <label for="content">Content</label>
    <textarea name="post[content]" id="content"><%=@post.content%></textarea>

    <h3>Subs to Post to</h3>
    <%Sub.all.each do |sub|%>
        <br>
        <label><%=sub.title%>
        <input type="checkbox" 
            name="post[sub_ids][]" 
            value="<%=sub.id%>"
            <%= "checked" if @post.sub_ids.include?(sub.id)%>>
        </label>
    <%end%>
    <br>
    <input type="submit" value="Submit">
</form>

my_reddit/app/views/posts/new.html.erb
<h1>New Post!</h1>

<form action="<%=posts_url%>" method="post">
        <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
        <label for="title">Title</label>
        <input type="text" id="title" name="post[title]">
        <br>
        <label for="url">URL</label>
        <input type="text" id="url" name="post[url]">
        <br>
        <label for="content">Content</label>
        <textarea name="post[content]" id="content"></textarea>

        <h3>Subs to Post to</h3>
        <%Sub.all.each do |sub|%>
            <br>
            <label><%=sub.title%>
            <input type="checkbox" 
                name="post[sub_ids][]" 
                value="<%=sub.id%>">
            </label>
        <%end%>
        <br>
        <input type="submit" value="Submit">
</form>
    

my_reddit/app/views/posts/show.html.erb
<h1><%=@post.title%></h1>

<a href="<%=edit_post_url(@post)%>">Edit This Post</a>
<br>
<%=@post.content%>
<br>
<%=@post.url%>
<br>
<%= @post.votes.reduce(0) {|sum, vote| sum+= vote.value} %>
<br>
<form action="<%= post_upvote_url(@post)%>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <input type="submit" value="Upvote">
</form>
<form action="<%= post_downvote_url(@post)%>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <input type="submit" value="Downvote">
</form>

<h3>Subs</h3>
<ul>
    <% @post.subs.each do |sub|%>
    <li><a href="<%=sub_url(sub)%>"><%=sub.title%></a></li> 
    <%end%>
</ul> 

<h2>Comments</h2>
<a href="<%=new_post_comment_url(@post)%>">Comment on this post</a>
<ul>
    <% @all_comments[nil].each do |comment| %>
        <li><a href="<%= comment_url(comment) %>"><%=comment.content%></a></li>
        <%=render 'comment_tree', parent_comment: comment, all_comments: @all_comments%>
    <% end %>
</ul>