my_reddit/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  root to: 'subs#index'
  resources :subs
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    post :upvote
    post :downvote
  end
  resources :comments, only: [:create, :show, :destroy]

end

my_reddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint(8)        not null, primary key
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#

class Sub < ApplicationRecord
    
    validates :title, :description, :moderator_id, presence: true
    validates :title, uniqueness: true

    belongs_to(
        :moderator,
        class_name: 'User',
        foreign_key: :moderator_id
    )

    has_many(
        :subtags
    )
    has_many :posts,
    through: :subtags,
    source: :post
end

my_reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :require_login
  
  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    #TODO redirect if not moderator and hide edit button from others
  end

  def update
    @sub = Sub.find(params[:id])
    if current_user.id == @sub.moderator_id && @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      flash[:errors] = "You Are not the Moderator" if current_user.id == @sub.moderator_id
      render :edit
    end
  end

  def index
    #maybe filter logic from query string
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

my_reddit/app/helpers/subs_helper.rb
module SubsHelper
end

my_reddit/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<form action="<%=sub_url(@sub)%>" method="post">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <label for="sub">Title</label>
    <input type="text" id="sub" name="sub[title]" value="<%=@sub.title%>">
    <br>
    <label for="description">Description</label>
    <input type="description" id="description" name="sub[description]" value="<%=@sub.description%>">
    <br>
    <input type="submit" value="Update Sub">
</form>

my_reddit/app/views/subs/index.html.erb
<h1>All Subs</h1>

<ul>
    <% @subs.each do |sub| %>
        <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
    <% end %>
</ul>

<a href="<%= new_sub_url %>">New Sub</a>

my_reddit/app/views/subs/new.html.erb
<h1>Create Sub</h1>


<form action="<%=subs_url%>" method="post">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <label for="sub">Title</label>
    <input type="text" id="sub" name="sub[title]">
    <br>
    <label for="description">Description</label>
    <input type="description" id="description" name="sub[description]">
    <br>
    <input type="submit" value="Create Sub">
</form>

my_reddit/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<p><%= @sub.description %></p>

<a href="<%=new_post_url%>">Make a New Post!</a>
<br>
<ul>
    <% @sub.posts.each do |post|%>
    <li><a href="<%=post_url(post)%>"><%=post.title%></a></li> 
    <%end%>
</ul> 

<br>
<a href="<%= edit_sub_url(@sub) %>">Edit Sub</a>
<p>Moderated by <%= @sub.moderator.username %></p>